version: '3.1'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USER}
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
volumes:
    postgres:
